### ISSUE TITLE
pipenv lock -r?

### ISSUE THREAD

**Issue by haizaar** [Stibbons/pipenv-to-requirements#11]
Good day,

I wonder why do I need this package if `pipenv lock -r` is there?
Can you please elaborate?

**Comment by gsemet** [comment]
Indeed I should add a comparison. The main goal is to recreate both requirement.twt (from package section of the Pipfile) and requirements-dev.txt (from dev-package). To my understanding pipenv lock -r will dump the current env (dev or not-dev) to requirements.txt, so you cannot only get the non-dev packages from you dev environment.

**Comment by haizaar** [comment]
Nope, it all works reasonably :)
```
$ cd $(mktemp -d)
$ pipenv install idna; pipenv install --dev bar  # Yes, there is a package called bar. No foo :(
$ cat Pipfile
...
[packages]
idna = "*"

[dev-packages]
bar = "*"
...
$ pipenv lock -r
-i https://pypi.org/simple
idna==2.7
$ pipenv lock -r --dev
-i https://pypi.org/simple
bar==0.2.1
```
I.e. `lock -r` includes only install deps, and `lock -r --dev` only deps.

**Comment by gsemet** [comment]
Ok this project might be replaced by pipenv lock -r alone now. If you look at the code it does not do fancy stuff, but I need to keep requirements.txt in sync with the Pipfile for PBR to be happy, somehow.

**Comment by haizaar** [comment]
Thanks for explaining!
