### ISSUE TITLE
Ignores environment markers and package sources

### ISSUE THREAD

**Issue by con-f-use** [Stibbons/pipenv-to-requirements#12]
Ignores [Pep 508](https://www.python.org/dev/peps/pep-0508/) environment markers in the pipfile.

The following Pipfile:

    [packages]
    libvirt-python = {version = "==4.10.0", platform_system = "== 'Linux'"}

Results in the `reqirement.txt` line:

    libvirt-python==4.10.0    

rather than the correct:

    libvirt-python==4.10.0; platform_system == 'Linux'

**Comment by con-f-use** [comment]
@gsemet do you still maintain this project?

**Comment by gsemet** [comment]
Hi. Yes I maintain it but have no time to improve it. Pull requests are welcome !

**Comment by con-f-use** [comment]
Good to hear, I'm pretty busy myself, but I'll see what I can do.

In the mean time, this seems to fail, too:

```
[packages]
libvirt-python = {version = "==4.10.0", markers="platform_system=='Linux'"}
```

Output:

```
libvirt-python==4.10.0
```

I thought I saw a testcase for the markers somewhere in the code?

**Comment by con-f-use** [comment]
Seems like the culprit was `formatPipenvEntryForRequirements`, which removed the markers.
All the test were passing, because they only used `parse_pip_file` instead. No idea why `formatPipenvEntryForRequirements` existed in the first place.
